require 'nester'
require 'ffi'

## if ccinfo.is_windows then
local libpath: cstring = "ffi_module.dll"
## else
local libpath: cstring = "./ffi_module.so"
## end

local lib: ffi
nester.describe("ffi", function()
  nester.it("load", function()
    lib = ffi.load(libpath)
    expect.truthy(lib:isloaded())
  end)

  nester.it("get", function()
    local f42 = (@function(): cuint)(lib:get("f42"))
    expect.not_equal(f42, nilptr)
    expect.equal(f42(), 42)
  end)

  nester.it("unload", function()
    assert(lib:unload() == true)
    assert(lib:unload() == false)
  end)
end)
